/**
 * Interop test for issue #289: @axionvera/codegen is independently importable,
 * and @axionvera/core's codegen surface still re-exports it (backward compat).
 *
 * The new package is consumed via its built `dist` (npm workspace symlink), so
 * it must be built + linked before this runs. The backward-compat assertion
 * targets the core re-export shim (`packages/core/src/codegen`) — the same deep
 * import style the existing codegen.test.ts uses — rather than the @axionvera/core
 * barrel, whose build is pre-broken by unrelated modules (contracts/Vault,
 * test/msw/setup) outside the scope of this extraction.
 */
import { parseWasm, generateContractClass, type ContractSpec } from '@axionvera/codegen';
import * as coreCodegen from '../packages/core/src/codegen';

const spec: ContractSpec = { functions: [], structs: [], enums: [] };

describe('@axionvera/codegen package interoperability', () => {
  it('exposes parseWasm and generateContractClass', () => {
    expect(typeof parseWasm).toBe('function');
    expect(typeof generateContractClass).toBe('function');
  });

  it('generates a contract client class from a spec', () => {
    const src = generateContractClass(spec, 'DemoContract');
    expect(src).toContain('class DemoContract extends BaseContract');
    expect(src).toContain('Auto-generated by axionvera-cli codegen');
  });

  it('is still re-exported by @axionvera/core (backward compat shim)', () => {
    expect(typeof coreCodegen.generateContractClass).toBe('function');
    expect(typeof coreCodegen.parseWasm).toBe('function');
    // Behavioral parity: the re-export produces identical output.
    expect(coreCodegen.generateContractClass(spec, 'DemoContract')).toBe(
      generateContractClass(spec, 'DemoContract')
    );
  });
});
